repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: ^backup/
    -   id: ruff-format
        exclude: ^backup/
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
